nome = input('Digite seu nome: ')
search = ('Silva' in nome)
print('Se seu nome tiver Silva, a palavra que irá aparecer será True.')
print('Se seu nome não tiver Silva, a palavra que irá aparecer será False.')
print(f'Resultado: {search}')